name: JVM SDK

on:
  push:
    paths:
      - "jvm/**"
      - ".github/workflows/jvm.yml"
      - "codegen/openapi.json"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jvm
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run lint
        run: ./gradlew ktlintCheck
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jvm
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
  docs:
    name: Publish API reference
    needs: [build, check]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: ./jvm
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run dokka
        run: ./gradlew dokkaHtml
      - name: Deploy on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./jvm/lib/build/dokka/html
          destination_dir: jvm
  release:
    name: Release
    needs: [check, build]
    if: ${{ startsWith(github.ref, 'refs/tags/jvm-v') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jvm
    environment:
      name: Maven
      url: https://central.sonatype.com/artifact/io.portone/server-sdk
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish package
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
